### PR TITLE
Update bootstrap url

### PR DESCRIPTION
**Pull request by arlyon**
Fixes issue #4

### CODE REVIEW

**Comment by mturley** [comment]
@gammons Is this frontend still maintained?  @arlyon do you have any interest in rebasing this PR and trying to get it to pass CI?  Would love to use this web frontend but it's broken without bootstrap.

**Comment by arlyon** [comment]
Could do but if it fails because of "eval yarn" its got nothing to do with my code...

**Comment by gammons** [comment]
gah, I know, I need to give this project some love.   going to see if I can get this straightened out tomorrow.

**Comment by gammons** [comment]
the `index.html` is actually servied by the `todolist` binary.  there's a PR that will fix this here:  https://github.com/gammons/todolist/pull/115

**Comment by mturley** [comment]
Woo, thanks @gammons !  Really love your work with `todolist`. It's the main thing keeping me on track these days.

**Pull request closed without merging**
